### ISSUE TITLE
need node v16.x, not v17.x

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#46]
There is a [known problem](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported) with node v17.x and webpack that also affects our app (currently).

If I run our app on node v17.5.0, I get:

<details>
<summary>trace</summary>

```bash
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/surchs/Repositories/MNI/annotation_tool/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/surchs/Repositories/MNI/annotation_tool/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/surchs/Repositories/MNI/annotation_tool/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/surchs/Repositories/MNI/annotation_tool/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/surchs/Repositories/MNI/annotation_tool/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/surchs/Repositories/MNI/annotation_tool/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/surchs/Repositories/MNI/annotation_tool/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/surchs/Repositories/MNI/annotation_tool/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/surchs/Repositories/MNI/annotation_tool/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/surchs/Repositories/MNI/annotation_tool/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/surchs/Repositories/MNI/annotation_tool/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```
</details>

The fix for now is to downgrade to v16.x. I tested with v16.13.0 and it worked fine.

Something to consider adding to the docs.

**Comment by surchs** [comment]
OK, let's add this guy to the readme and then close here. t'is getting a bit silly.

**Comment by surchs** [comment]
OK, new goal: close this issue before it is one year old :crossed_fingers:

**Comment by surchs** [comment]
We'll address the bigger issue of outdated dependencies and security vulnerabilities orgwide here: https://github.com/neurobagel/project/issues/69
